apiVersion: v1
kind: Service
metadata:
    name: hello-node-svc
spec:
    type: ClusterIP
    selector:
        app: hello-node
    ports:
        - protocol: TCP
          port: 4000
          targetPort: 3335
