apiVersion: v1
kind: Secret
metadata:
    name: mysecret2
type: Opaque
data:
    username: ENC[AES256_GCM,data:MXjPZukHK/8=,iv:1TqEqKXw8oc5b8hdbD7OgaFjmHe+tQ4E06y1NgfIjVA=,tag:v4MbgDiKZdGjgDSmo7yhMg==,type:str]
    password: ENC[AES256_GCM,data:cZjRJk+QatWRKmIIH62qLA==,iv:slQetJKaUrv56JPSKKEirMGG1LsrVUEYWCi/4FiyoNk=,tag:qpWzB/+V39c63g4ZSGqf0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16dl9tg08c4wdfp8qe4msxlnvz448u8ak8qx5xlv77fzd45utackq26jd7y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOVJhSktSSThPZURPMmhj
            NFVzTm5nc0dzN3VVbG13OGd5WE9JTUhaT0VnCnVHMFNJTldDMzh6VkhWbFJVNE1H
            UWh2eHZ1cExLMkdwTEZvUUhtM3BDUWcKLS0tIDBlVzZOUUNZcHVBT1pSZDJzMEp4
            cFlxbnFxT3ZpZENMdUUzRm1abnpFTU0KAA6U+kRlMVAL3iDUcdfLZSAil28UISfW
            5LfPojP/OIg2492M4/OyBj5R9b95zjQGdeoS9v+4e4z57doHf1doFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-08T21:25:50Z"
    mac: ENC[AES256_GCM,data:hU1k4lGVtamh4nnHq7LDdQtR2gHQLE80Zc6RUvOBmDPXxlmP+MRfKEU6bfZNrXOxaAp52N9XEpiyaO3iWom6zJcs8iLzL+5O3RrrfuEdiDzz+uJqPP2d8EbQIYQTp154cI5lASqbpdqY2ZtiGHbrQ7q+TRAaijETtDZdpK2B0KU=,iv:Ex18daEDsQCm5hmHc+jXFr0SnpvbhAqXJwv5DLL+Dvs=,tag:kJJc0iuxbv5jPnlaYxFmgA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
